# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.19.2



# Mod Properties
mod_version = 1.23.0
maven_group = net.hyper_pigeon
archives_base_name = eldritch-mobs

# Dependencies
fabric_version=0.141.3+1.21.11
cardinal_version=7.3.1
modmenu_version=17.0.0
config_version=21.11.153
polymer_version=0.15.2+1.21.11
polymer_blocks_version=0.15.2+1.21.11
server_translation_api_version=2.5.2+1.21.9-pre3